title: living-in-harvard.7robots.org
description: A Natural History of the Shaker Village Historic District in Harvard, MA
theme: just-the-docs

url: https://living-in-harvard.7robots.org

logo: "/assets/Moon.jpeg"
color_scheme: dark
nav_external_links_new_tab: true

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
